### ISSUE TITLE
Missing scikit-learn Dependency in Docker Image

### ISSUE THREAD

**Issue by FasihMunirMalik** [christianbirchler-org/sdc-testing-competition#26]
**Description**:  
A recent update introduced the use of `scikit-learn` in the evaluation.py file, specifically functions like `pairwise_distances` from `sklearn.metrics.pairwise`. However, `scikit-learn` is not currently installed in the Evaluator Docker image, which leads to an import error when running the container.

**Steps to Reproduce**:
1. Build latest Docker image.
2. Run the container.
3. Observe the import error for `scikit-learn`.

**Current Behavior**:  
Running the Docker container results in an error indicating that `scikit-learn` is missing.

**Expected Behavior**:  
The Docker image should have `scikit-learn` installed so that functions like `pairwise_distances` work without errors.

**Suggested Fix**:  
Add `scikit-learn` to the Evaluator Dockerfile. For example, you could include:
   ```dockerfile
   RUN pip install scikit-learn
   ```

This would ensure that `scikit-learn` is available in the container, allowing for successful execution of scripts that depend on it.

Thank you for addressing this issue!

**Comment by ChristianBirchler** [comment]
fixed in v1.1.8
